### ISSUE TITLE
Versioning Relationships Using neo4j-versioner-core

### ISSUE THREAD

**Issue by aggarwal-mayank** [h-omer/neo4j-versioner-core#4]
Hi

I am currently working on a Neo4J project where we need to implement versioning for both Entities and Relationships, I saw your online meetup video and found your implementation meeting all that we need for versioning Entities. Also, you touched on the topic of versioning Relationships, can you share any examples where you have implemented it or any way to do it via the neo4j-versioner-core (In your video you demo something similar in versioner-sql).
You have talked about setting it up as a milestone, have you published anything regarding the same.

Thanks in advance...

**Comment by albertodeste** [comment]
Hi,

thank you for giving us a feedback. It helps us feel we're doing something useful.

You, like other people last year, are asking for this feature so this suggests me to add a milestone with an ipothetical date for the release of this feature. Since this will be a big change in the way of versioning Neo4j entities, we are releasing this feature as a major version (as of now it will be the 2.0.0 release).
If you switch branch (2.0.0) on this repository you'll find the work in progress version including the working implementation of the versioning for the "init" method. We're planning changes also on other support methods, like "update", as well as new methods to support this specific feature.

I think that it might be useful to release the documentation, as a draft, for the new relationships versioning, as soon as possible, so people like you can give us feedbacks on the ideas we'll implement in next days/months.

Let me know if I'm missing something.

**Comment by ncrocfer** [comment]
Hi,

First of all thank you for these awesome procedures :) I looked at your 2.0 branch and it seems the work is almost done for the relationships versioning. Do you think it will soon be merged in master please?

**Comment by mfalcier** [comment]
Hi! Thank your for your support 👍 

I hope it will be released soon. 
We are working on the implementation of the recursive relationship update and on the full integration with the new Neo4j 3.4.x (i.e. native DateTime support).

**Comment by trustiser** [comment]
Hi,
any news about 2.0 version which support relationships versionning ???

**Comment by mfalcier** [comment]
With the 2.0.0 release, now relationship can be versioned.
