### ISSUE TITLE
Several procedures are not available under version 1.3 + Neo4j Community 3.4.5 + Browser 3.2.5

### ISSUE THREAD

**Issue by gbwzxgbw** [h-omer/neo4j-versioner-core#6]
We're trying this amazing feature after watching your video.
The 'init' and 'patch' work perfectly and all behaviors are as expected.
When I execute 'get.current.state', it prompts me that ProcedureNotFound.

Here is the result of graph.versioner.* from dbms.procedures()
"graph.versioner.diff"
"graph.versioner.diff.from.current"
"graph.versioner.diff.from.previous"
"graph.versioner.init"
"graph.versioner.patch"
"graph.versioner.patch.from"
"graph.versioner.rollback"
"graph.versioner.rollback.nth"
"graph.versioner.rollback.to"
"graph.versioner.update"

Neo4j-Versioner-Core version: 1.3
Neo4j Server version: Community 3.4.5
Neo4j Browser version: 3.2.5

Please let me know if anything I missed.
Thank you for your excellent work.

**Comment by mfalcier** [comment]
Hi @gbwzxgbw and thanks for your support and for opening this issue!

Unfortunately at the moment neo4j-versioner-core does not support, at its latest release (1.3.0), Neo4j 3.4x. 

Theoretically, we already solved this issue in version 2.0.0: If you want you can clone this project and build your own jar, so you can use it and test; otherwise if you can't, tell me and I'll build the library for you.

**Comment by mfalcier** [comment]
Meanwhile I've build it for you, so you can try easily 👍 
[neo4j-versioner-core-2.0.0.jar.zip](https://github.com/h-omer/neo4j-versioner-core/files/2283372/neo4j-versioner-core-2.0.0.jar.zip)

**Comment by mfalcier** [comment]
With our latest 2.0.0 update, we added support for version 3.5.1.
